version: '3.8'

services:
  # 1. Django Web Service (HTTP 요청 처리)
  web:
    build: .
    env_file:
      - .env
    # Gunicorn Timeout 5분 설정 유지
    command: gunicorn pdfuploader.wsgi:application --bind 0.0.0.0:8000 --timeout 300
    volumes:
      - .:/app
      - shared_data:/tmp/celery_jobs
    ports:
      - "127.0.0.1:8000:8000"
    # Web 서비스에 restart 정책 추가
    restart: on-failure
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - default
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64


  # 2. Redis Message Broker Service (Celery Broker)
  redis:
    image: redis:6-alpine
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5
      start_period: 5s
    ports:
      - "6379:6379"
    networks:
      default:
        aliases:
          - redis_host
          - redis_master

  # 3. Celery Worker Service (OCR/PDF 연산 수행)
  celery_worker:
    build: .
    env_file:
      - .env
    command: celery -A pdfuploader worker -l debug
    volumes:
      - .:/app
      - shared_data:/tmp/celery_jobs
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - default
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
networks:
  default:
    name: pdf_mask_v2_default_net
volumes:
  shared_data: